export const SET_DATA_FROM_LOCAL_STORAGE = 'SET_DATA_FROM_LOCAL_STORAGE';
export const SET_DATA_FROM_GITHUB_API = 'SET_DATA_FROM_GITHUB_API';
export const SET_ERROR_FROM_GITHUB_API = 'SET_ERROR_FROM_GITHUB_API';
export const SET_SORTED_DATA = 'SET_SORTED_DATA';
