export const GET_DATA_FROM_LOCAL_STORAGE = 'GET_DATA_FROM_LOCAL_STORAGE';
export const GET_DATA_FROM_GITHUB_API = 'GET_DATA_FROM_GITHUB_API';
export const GET_ERROR_FROM_GITHUB_API = 'GET_ERROR_FROM_GITHUB_API';
export const SORT_DATA = 'SORT_DATA';